#!/usr/bin/env python3
"""Auto-fill journal nightly — aggregates signals_received.csv outcomes for the day."""
import sys
import argparse
import csv
import os
from datetime import datetime, timezone, timedelta
from pathlib import Path


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--profile", required=True)
    p.add_argument("--date", default="", help="YYYY-MM-DD; default today")
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()

    target_date = args.date or datetime.now(timezone.utc).strftime("%Y-%m-%d")

    profiles_dir = Path(os.environ.get("WALLY_PROFILES_DIR", ".claude/profiles"))
    csv_path = profiles_dir / args.profile / "memory" / "signals_received.csv"
    journal_path = profiles_dir / args.profile / "memory" / "trading_log.md"

    if not csv_path.exists():
        print(f"WARNING: No CSV at {csv_path}", file=sys.stderr)
        sys.exit(1)

    # Aggregate today's trades
    today_trades = []
    with open(csv_path) as f:
        for row in csv.DictReader(f):
            ts_str = row.get("ts") or row.get("timestamp") or row.get("date") or ""
            if target_date in ts_str:
                today_trades.append(row)

    if not today_trades:
        msg = f"No trades on {target_date}"
        print(f"INFO: {msg}")
        sys.exit(0)

    # Compute summary
    pnls = []
    wins = 0
    losses = 0
    for t in today_trades:
        try:
            pnl = float(t.get("pnl_usd") or 0)
        except ValueError:
            pnl = 0
        pnls.append(pnl)
        if pnl > 0:
            wins += 1
        elif pnl < 0:
            losses += 1

    total_pnl = sum(pnls)
    n = len(today_trades)
    wr = wins / n * 100 if n else 0

    # Generate markdown entry
    entry = f"""
## {target_date} — Auto-summary ({args.profile})

- **Trades:** {n} ({wins} wins / {losses} losses) — WR {wr:.0f}%
- **Total PnL:** ${total_pnl:+.2f}
- **Best:** ${max(pnls):+.2f} | **Worst:** ${min(pnls):+.2f}
- **Avg:** ${(total_pnl/n if n else 0):+.2f}/trade

### Trades del dia

"""
    for t in today_trades:
        entry += f"- {t.get('symbol', '?')} {t.get('side', '?')} @ {t.get('entry', '?')} -> {t.get('outcome', 'pending')}: ${t.get('pnl_usd') or '?'}\n"

    entry += "\n_Auto-generated by journal_autofill.py_\n\n---\n"

    if args.dry_run:
        print(entry)
    else:
        journal_path.parent.mkdir(parents=True, exist_ok=True)
        with open(journal_path, "a") as f:
            f.write(entry)
        print(f"Appended {n}-trade summary to {journal_path}")


if __name__ == "__main__":
    main()
